sudo: required
services:
  - docker

before_install:
  - docker build -t srikar/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true srikar/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"  
  bucket_name: "elasticbeanstalk-ap-south-1-590183999582"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  